services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.production
    volumes:
      - app_logs:/var/log/app
      - post_uploads_data:/data/post_uploads
      - profile_uploads_data:/data/uploads
      - comment_uploads_data:/data/comment_uploads
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Waiting for MySQL to be ready...'
        until nc -z db 3306; do
          sleep 3
        done
        echo 'MySQL is up - running migrations and starting backend'
        python migrate.py &&
        gunicorn --bind 0.0.0.0:5000 --log-level=info wsgi:app
      "
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - ./.env.production
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env.production
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: >
      sh -c "
        until [ -f /etc/letsencrypt/live/$$CERTBOT_DOMAIN/fullchain.pem ]; do
          echo 'Nginx is waiting for certificate...'
          sleep 5
        done;
        echo 'Certificate found. Starting Nginx...';
        nginx -g 'daemon off;'
      "
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    env_file:
      - ./.env.production
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "
        sleep 10 && 
        certbot certonly --webroot -w /var/www/certbot --email $$CERTBOT_EMAIL
        --agree-tos --no-eff-email --rsa-key-size 4096 --expand --force-renewal 
        -d $$CERTBOT_DOMAIN 
        -d www.$$CERTBOT_DOMAIN &&
        echo 'Certificates obtained. Nginx will start automatically.'
      "
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  app_logs:
  post_uploads_data:
  profile_uploads_data:
  comment_uploads_data:
