services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - app-network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.production
    volumes:
      - app_logs:/var/log/app
      - post_uploads_data:/data/post_uploads
      - profile_uploads_data:/data/uploads
      - comment_uploads_data:/data/comment_uploads
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - ./.env.production
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  app_logs:
  post_uploads_data:
  profile_uploads_data:
  comment_uploads_data:
