version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.development
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - leonardo-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - app_logs:/var/log/app
      - post_uploads_data:/data/post_uploads
      - profile_uploads_data:/data/uploads
      - comment_uploads_data:/data/comment_uploads
    depends_on:
      - db
    entrypoint: >
      sh -c "
        until nc -z db 3306; do
          echo 'Waiting for MySQL to be ready...'
          sleep 3
        done
        echo 'MySQL is up - running migrations and starting backend'
        python migrate.py &&
        python main.py
      "
    networks:
      - leonardo-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - leonardo-network

networks:
  leonardo-network:
    driver: bridge

volumes:
  mysql_data:
  app_logs:
  post_uploads_data:
  profile_uploads_data:
  comment_uploads_data:
