"""Initial migration

Revision ID: 26a8f71f7ffe
Revises: 
Create Date: 2025-06-15 07:56:48.940548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26a8f71f7ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_unique_constraint('user_post_uc', 'likes', ['user_id', 'post_id'])
    op.drop_constraint('likes_ibfk_1', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('key', sa.String(length=64), nullable=True))
    op.drop_column('users', 'post_limit')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('post_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'key')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_ibfk_1', 'likes', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('user_post_uc', 'likes', type_='unique')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_3', 'comments', 'users', ['user_id'], ['user_id'])
    op.alter_column('comments', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###