name: The Leonardo's Discussion Room CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
   deploy_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: "Deploy to staging"
        run: echo "Deploying to staging environment"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Download source-code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: leonardo-app
          
      - name:  Docker compose start
        run: |
          cd leonardo-app
          docker-compose -f docker-compose-dev.yml up -d
        timeout-minutes: 2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:5173'
          cmd_options: '-a'

      - name: Docker Compose Teardown
        run: |
          cd leonardo-app
          docker-compose -f docker-compose-dev.yml down
